Script started on 2015年03月16日 (週一) 20時17分17秒
]0;F74006399@2015cpp: ~/lab1/lab1F74006399@2015cpp:~/lab1/lab1$ whoami; pe[Kwd
F74006399
/home/F74006399/lab1/lab1
]0;F74006399@2015cpp: ~/lab1/lab1F74006399@2015cpp:~/lab1/lab1$ git config -l
user.name=bgrffqq
user.email=su3g4284zo6y7@gmail.com
color.diff=auto
color.status=auto
color.branch=auto
color.log=auto
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
remote.origin.url=https://github.com/bgrffqq/lab1.git
branch.master.remote=origin
branch.master.merge=refs/heads/master
]0;F74006399@2015cpp: ~/lab1/lab1F74006399@2015cpp:~/lab1/lab1$ git clone https://github.com/bgrffqq/;ab1.[K[K[K[K[Klab1.git
Cloning into 'lab1'...
remote: Counting objects: 11, done.[K
remote: Compressing objects:  11% (1/9)   [Kremote: Compressing objects:  22% (2/9)   [Kremote: Compressing objects:  33% (3/9)   [Kremote: Compressing objects:  44% (4/9)   [Kremote: Compressing objects:  55% (5/9)   [Kremote: Compressing objects:  66% (6/9)   [Kremote: Compressing objects:  77% (7/9)   [Kremote: Compressing objects:  88% (8/9)   [Kremote: Compressing objects: 100% (9/9)   [Kremote: Compressing objects: 100% (9/9), done.[K
remote: Total 11 (delta 1), reused 11 (delta 1), pack-reused 0[K
Unpacking objects:   9% (1/11)   Unpacking objects:  18% (2/11)   Unpacking objects:  27% (3/11)   Unpacking objects:  36% (4/11)   Unpacking objects:  45% (5/11)   Unpacking objects:  54% (6/11)   Unpacking objects:  63% (7/11)   Unpacking objects:  72% (8/11)   Unpacking objects:  81% (9/11)   Unpacking objects:  90% (10/11)   Unpacking objects: 100% (11/11)   Unpacking objects: 100% (11/11), done.
]0;F74006399@2015cpp: ~/lab1/lab1F74006399@2015cpp:~/lab1/lab1$ exit

Script done on 2015年03月16日 (週一) 20時18分17秒
